apiVersion: v1
kind: ServiceAccount
metadata:
  name: packetloss-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packetloss-scheduler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler
subjects:
  - kind: ServiceAccount
    name: packetloss-scheduler
    namespace: kube-system
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: packetloss-scheduler-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: packetloss-scheduler
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packetloss-scheduler
  namespace: kube-system
  labels:
    app: packetloss-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packetloss-scheduler
  template:
    metadata:
      labels:
        app: packetloss-scheduler
    spec:
      serviceAccountName: packetloss-scheduler
      nodeSelector:
        kubernetes.io/hostname: kubetest2
      containers:
        - name: scheduler
          image: kubetest5:5000/packetloss-scheduler
          imagePullPolicy: Always
          command:
            - /app/packetloss-scheduler
            - --config=/app/scheduler-config.yaml
            - --kubeconfig=/app/config
          volumeMounts:
            - name: scheduler-config
              mountPath: /app/scheduler-config.yaml
              readOnly: true
            - name: kube-config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: scheduler-config
          hostPath:
            path: /etc/kubernetes/scheduler-config.yaml
            type: File
        - name: kube-config
          hostPath:
            path: /home/adam/.kube/config
            type: File
