apiVersion: v1
kind: ServiceAccount
metadata:
  name: packetloss-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packetloss-scheduler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler
subjects:
  - kind: ServiceAccount
    name: packetloss-scheduler
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-scheduler-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
    resourceNames: ["extension-apiserver-authentication"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-scheduler-rolebinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: packetloss-scheduler
    namespace: kube-system
roleRef:
  kind: Role
  name: custom-scheduler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packetloss-scheduler
  namespace: kube-system
  labels:
    app: packetloss-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packetloss-scheduler
  template:
    metadata:
      labels:
        app: packetloss-scheduler
    spec:
      serviceAccountName: packetloss-scheduler
      nodeSelector:
        kubernetes.io/hostname: kubetest2
      containers:
        - name: scheduler
          image: kubetest5:5000/packetloss-scheduler
          imagePullPolicy: Always
          command:
            - /app/packetloss-scheduler
            - --config=/app/scheduler-config.yaml
            - --master=http://kubetest2.adam.bucior.pl:6443
          volumeMounts:
            - name: scheduler-config
              mountPath: /app/scheduler-config.yaml
              readOnly: true
            - name: kube-config
              mountPath: /app/config
      volumes:
        - name: scheduler-config
          hostPath:
            path: /etc/kubernetes/scheduler-config.yaml
            type: File
        - name: kube-config
          hostPath:
            path: /home/adam/.kube/config
            type: File
