apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-apps-backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kubetest5:5000/kube-apps-backend
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-secret
          env:
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: postgres-svc
            - name: REDIS_HOST
              value: redis-svc
---
apiVersion: v1
kind: Service
metadata:
  name: kube-apps-backend-entry
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      nodePort: 30002
