apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-node-monitor
  labels:
    app: node-monitor
spec:
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      containers:
        - name: node-monitor
          image: kubetest5:5000/kube-node-monitor
          imagePullPolicy: Always
          env:
            - name: K8S_NODE
              valueFrom:
                fieldRef:
                  fieldPath: "spec.nodeName"
            - name: DELAY_THRESHOLD_MS
              value: "100"
            - name: PACKET_LOSS_THRESHOLD
              value: "3"
      tolerations:
        - key: "kubetest-unavailable"
          operator: "Exists"
