apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-monitor-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-monitor-clusterrole
rules:
  # Grant full access to all resources in all API groups
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-monitor-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: node-monitor-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: node-monitor-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-node-monitor
  labels:
    app: node-monitor
spec:
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      serviceAccountName: node-monitor-account
      containers:
        - name: node-monitor
          image: kubetest5:5000/kube-node-monitor
          imagePullPolicy: Always
          env:
            - name: K8S_NODE
              valueFrom:
                fieldRef:
                  fieldPath: "spec.nodeName"
            - name: DELAY_THRESHOLD_MS
              value: "100"
            - name: PACKET_LOSS_THRESHOLD
              value: "3"
      tolerations:
        - key: "kubetest-unavailable"
          operator: "Exists"
